title: Peter J. Lu
description: redirect links from (old) peterlu.org to (new) peterlu.com

markdown: kramdown
theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
